// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8yH0AMiCrEQmV9qDMCnam5sxncOxSduA',
    appId: '1:1001554723948:web:d6f9e40fe0e84d6c8d0449',
    messagingSenderId: '1001554723948',
    projectId: 'ordertracking-f4874',
    authDomain: 'ordertracking-f4874.firebaseapp.com',
    storageBucket: 'ordertracking-f4874.firebasestorage.app',
    measurementId: 'G-9DVS9ZEZYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBa5Mbnqf1M0rGHpedfI3n2x_23T_chS4',
    appId: '1:1001554723948:android:17c6c5510e38c1538d0449',
    messagingSenderId: '1001554723948',
    projectId: 'ordertracking-f4874',
    storageBucket: 'ordertracking-f4874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_IeVhgtfYqRlGlg_vwMc5k4-2Jfl9po',
    appId: '1:1001554723948:ios:4a8a0877e892c5168d0449',
    messagingSenderId: '1001554723948',
    projectId: 'ordertracking-f4874',
    storageBucket: 'ordertracking-f4874.firebasestorage.app',
    iosBundleId: 'com.example.ordertracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_IeVhgtfYqRlGlg_vwMc5k4-2Jfl9po',
    appId: '1:1001554723948:ios:4a8a0877e892c5168d0449',
    messagingSenderId: '1001554723948',
    projectId: 'ordertracking-f4874',
    storageBucket: 'ordertracking-f4874.firebasestorage.app',
    iosBundleId: 'com.example.ordertracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8yH0AMiCrEQmV9qDMCnam5sxncOxSduA',
    appId: '1:1001554723948:web:1e9a32cc1ee213608d0449',
    messagingSenderId: '1001554723948',
    projectId: 'ordertracking-f4874',
    authDomain: 'ordertracking-f4874.firebaseapp.com',
    storageBucket: 'ordertracking-f4874.firebasestorage.app',
    measurementId: 'G-VQWK2T5KF5',
  );
}
